# Generated by Django 2.0.3 on 2018-03-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=70)),
                ('telefono', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=70)),
                ('telefono', models.CharField(blank=True, max_length=13)),
                ('calle', models.CharField(max_length=50)),
                ('numero_int', models.CharField(blank=True, max_length=50)),
                ('numero_ext', models.CharField(blank=True, max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('lat', models.CharField(blank=True, max_length=20)),
                ('lng', models.CharField(blank=True, max_length=20)),
                ('zona', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
