# Generated by Django 2.0.3 on 2018-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_cliente_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(max_length=5),
        ),
    ]
