# Generated by Django 2.0.3 on 2018-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20180425_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
