# Generated by Django 2.0.3 on 2018-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20180430_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
