# Generated by Django 2.0.3 on 2018-04-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20180430_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.IntegerField(blank=True),
        ),
    ]
