# Generated by Django 2.0.3 on 2018-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_auto_20180512_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.IntegerField(blank=True),
        ),
    ]
