# Generated by Django 2.0.3 on 2018-04-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20180404_1707'),
        ('rutas', '0002_auto_20180414_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Cliente')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.Reporte')),                
            ],
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='clientes',
        ),
    ]
