# Generated by Django 2.0.3 on 2018-04-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_reporte_mapa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='chofer_nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_str',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
