# Generated by Django 2.0.3 on 2018-04-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_auto_20180419_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='mapa_url',
            field=models.CharField(max_length=4000),
        ),
    ]
